import { createSlice } from '@reduxjs/toolkit';

// Initial state for the user slice
const initialState = {
    isSignInOrSignUp:""
};

// Create a slice for user
const userSlice = createSlice({
  name: 'user',
  initialState,
  reducers: {
    setIsSignInOrSignUp(state, action) {
      state.isSignInOrSignUp = action.payload;
    },
  },
});

// Export the actions generated by createSlice
export const { setIsSignInOrSignUp } =
  userSlice.actions;

// Export the reducer to be added to the store
export default userSlice.reducer;
